version: '2.3'

services:
  go-form:
    build:
      context: .
    container_name: go-form
    ports:
      - "8000:8000"
    volumes:
     - $GOPATH/src:/go/src

  mysql:
    image: mysql:latest
    container_name: form-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: form
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./.persist/mysql:/data/db

  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    container_name: form-phpmyadmin
    environment:
      PMA_HOST: mysql
    ports:
      - "8081:80"
